baseURL = "https://main.d2qsv2txm0gsln.amplifyapp.com"
languageCode = "en-us"
title = "PK Flyer"
theme = "pkflyer"
[Params]
    primary = "#fb9dd9"
    bodyText = "#030303"
    background = "#f9f4c3"
