baseURL = "https://pkflyer.art"
languageCode = "en-us"
title = "PK Flyer"
theme = "pkflyer"
[Params]
    primary = "#fb9dd9"
    bodyText = "#030303"
    background = "#4aae0c"
    headerText = "darkblue"
[markup.goldmark.renderer]
unsafe= true