baseURL = "https://pkflyer-update.netlify.app"
languageCode = "en-us"
title = "PK Flyer"
theme = "base"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  description = "A collection of art, music, and events created and organized by Paul Karner."
  headerImage  = "images/header.png"
  author = "Tough Pixels"
  imageSizes = "1280 768 640 320"
  imageFormats = "webp png"
